### ISSUE TITLE
Doesn't work with 3.0.0

### ISSUE THREAD

**Issue by Monotek18** [Thog/nx-dreport#2]
I tried this tool with my Switch 3.0.0, but it doesn't delete the error logs.
(it worked with my 5.0.1 Switch)

I used this fork of hekate to get CFW working on 3.0.0:
https://github.com/CTCaer/hekate/releases

**Comment by marysaka** [comment]
I don't have a 3.0.x version anymore on any of my systems... I will try to fix that anyway
